import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center space-x-8 text-base font-medium py-6 mb-4">
          <Link href="/" className="transition-colors hover:text-foreground/80 text-lg">
            Home
          </Link>
          <Link href="/generate" className="transition-colors hover:text-foreground/80 text-lg">
            Generate
          </Link>
          <Link href="/saved" className="transition-colors hover:text-foreground/80 text-lg">
            Saved Recipes
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
