import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center justify-center space-x-4 text-base font-medium py-3 mb-6 bg-white/90 backdrop-blur-md border-b border-slate-200/60 shadow-sm">
          <Link href="/" className="px-3 py-2 rounded-md transition-all duration-200 hover:bg-slate-100 hover:text-slate-900 text-slate-600 font-medium text-sm">
            Home
          </Link>
          <Link href="/generate" className="px-3 py-2 rounded-md transition-all duration-200 hover:bg-slate-100 hover:text-slate-900 text-slate-600 font-medium text-sm">
            Generate
          </Link>
          <Link href="/saved" className="px-3 py-2 rounded-md transition-all duration-200 hover:bg-slate-100 hover:text-slate-900 text-slate-600 font-medium text-sm">
            Saved Recipes
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
